export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_FAILURE_ALERT = 'REQUEST_FAILURE_ALERT';
export const CLEAR_FAILURE_ALERT = 'CLEAR_FAILURE_ALERT';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
