export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_FAILURE_ALERT = 'REQUEST_FAILURE_ALERT';
export const CLEAR_FAILURE_ALERT = 'CLEAR_FAILURE_ALERT';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
